#!/bin/bash
TAG=dc
myuser=$(who | awk '{print $1}')

community_edge_repo="https://dl-cdn.alpinelinux.org/alpine/edge/community"

echo "
FROM python:3.10.4-alpine3.15

RUN apk add \
    zsh \
    zsh-syntax-highlighting \
    git \
    xclip \
    tmux \
    libstdc++ \
    nodejs \
    npm 

RUN apk add --repository=$community_edge_repo \
    neovim \
    black \
    py3-pylint \
    py3-requests \
    py3-numpy \
    py3-pandas
RUN npm install -g pyright

RUN adduser -D $myuser
ENV ZDOTDIR=/home/$myuser/.config/zsh
ENV TERM=st-256color

CMD /bin/zsh -c 'source ~/.zprofile && tmux new -s devcontainer'
" | docker build - -t $TAG
