#!/bin/bash
source dutils.sh


readonly APP=" dmpv"


show_progres() {
  i=0
  spin='-\|/'
  while [[ ! -s "$1" ]]; do
    i=$(( (i+1) %4 ))
    du::notify -r 1 -t 200 "Starting ${spin:$i:1}"
    sleep .1
  done 
  error="$(cat "$1" | tail -n 1 | grep "Error")"
  message="$(cat "$1" | head -n 1)"
  [[ -n "${error}" ]] && du::cnotify -r 1 "${message}"
}

run_mpv() {
  tmpfile="$(mktemp /tmp/dmpv-log.XXXXXX)"
  mpv "$1" >> "${tmpfile}" & show_progres "${tmpfile}"
  rm "${tmpfile}"
}

main() {
  url="$(du::grep_urls "$(xclip -selection c -o)")" && \
    run_mpv "${url}" || \
    du::cnotify "Unable to get url from clipboard."
}

main "$@"
