#!/bin/bash

source dutils.sh

readonly APP=" dbookmark"
readonly DATA="${XDG_DATA_HOME}/dbookmarks.txt"

add() { echo "${2//${2}/${2} }$1" >> "${DATA}"; }
del() { sed -i "\,${1:2},d" "${DATA}"; }

main() {
  declare -a bmrks
  declare -a prefs=("o" "e" "d")

  [[ ! -f "${DATA}" ]] && mkdir -p "$(dirname "${DATA}")" && touch "${DATA}"
  readarray -t bmrks < <(cat "${DATA}")
  url="$(dutils::grep_urls "$(xclip -selection c -o)")" && lst="a ${url}\n"
  for p in "${prefs[@]}"; do
    lst+="$(printf "${p} %s\n" "${bmrks[@]}")\n"
  done
  
  sel=$(echo -e "${lst}" | dmenu -l 10) || exit 0

  case "${sel:0:1}" in
    a) 
      alias=$(dutils::einput -p " Add alias to ${url} (optional):") || exit 0 
      add "${url}" "${alias}" && dutils::notify "Bookmark has been added."
      ;;
    o)
      url=$(dutils::grep_urls "${sel}") && xdg-open ${url} || \
        dutils::cnotify "Unable to identify URL in selected line: ${sel:2}"
      ;;
    e)
      alias=$(dutils::einput -p " Enter new alias for ${url}:") || exit 0 
      del "${sel}" && add "$(dutils::grep_urls "${sel}")" "${alias}" && \
        dutils::notify "Alias has changed."
      ;;
    d) del "${sel}" && dutils::notify "Bookmark has deleted." ;;
  esac
}

main "$@"
