#!/bin/bash

APP=" dbookmark"
DATA=$XDG_DATA_HOME/dbookmarks.txt
URLREGEX="(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$\+&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"
SEP="___"

[[ ! -f $DATA ]] && mkdir -p $(dirname $DATA) && touch $DATA

get_url() { echo "$1" | grep -aEo $URLREGEX; }
url=$(get_url $(xclip -selection c -o)) && prefa="a$SEP$url"

pref() { printf "$1$SEP%s\n" $(cat $DATA | sed "s, ,$SEP,g"); }
allprefs=($prefa $(pref o) $(pref e) $(pref d))
sel=$(printf "%s\n" ${allprefs[@]} | sed "s,$SEP, ,g" | dmenu -l 10)

notify() { notify-send -a "$APP" "$@"; }
add() { echo "${alias//$SEP/ }$url" >> $DATA; }
del() { sed -i "\,$(echo $sel | sed "s,^[de]\s,,"),d" $DATA; }
if [[ $sel =~ ^[a].* ]]; then
    alias="$(2>/dev/null | dmenu -p " Add alias to $url (optional):")$SEP"
    add && notify "Bookmark has been added." && exit 0

elif [[ $sel =~ ^[o].* ]]; then
    url=$(get_url "$sel") && xdg-open $url && exit 0
    notify -u critical "Unable to identify URL in selected line: $sel"

elif [[ $sel =~ ^[e].* ]]; then
    url=$(get_url "$sel")
    alias="$(2>/dev/null | dmenu -p " Enter new alias for $url:")$SEP" || exit 1
    del && add && notify "Alias has changed." && exit 0

elif [[ $sel =~ ^[d].* ]]; then
    del && notify "Bookmark has deleted." && exit 0
fi

