#!/bin/bash

DATA=$XDG_DATA_HOME/search_engines.txt
URLREGEX="(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

engines=($(cat $DATA))
query=$(printf "%s\n" ${engines[@]} | dmenu)

[[ -z $query ]] && exit 1

for i in ${engines[@]}; do
    qpref=$(echo $query | sed 's/:.*//')
    spref=$(echo $i | sed 's/:.*//')
    if [[ $qpref == $spref ]]; then
        url=$(echo $i | grep -aEo $URLREGEX)
        qbody=$(echo $query | sed 's/.*://' | sed -e 's/^[[:space:]]*//')
        xdg-open $(printf $url ${qbody// /+}) && exit 0
    fi
done

url=$(echo ${engines[0]} | grep -aEo $URLREGEX)
xdg-open $(printf $url ${query// /+}) && exit 0
