#!/bin/bash
status=$(cat /sys/class/power_supply/BAT0/status)

if [ "$status" = "Not charging" ]; then
    status="?"
elif [ "$status" = "Discharging" ]; then
    status="-"
elif [ "$status" = "Charging" ]; then
    status="+"
else
    status="Q"
fi
echo $(cat /sys/class/power_supply/BAT0/capacity)%$status
